<a href="https://colab.research.google.com/github/ponshivavel/python/blob/main/Pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python -m pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.2'

In [4]:
# 1. Data Frame
df = pd.DataFrame([11,22,33],columns=['Numbers'])
print(df)

   Numbers
0       11
1       22
2       33

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
 data = {
     'Name':['Asad','Kamil','Rose','Lily'],
     'Age':[21,20,18,19],
     'Salary':[9000,6700,5688,9500]
 }

In [7]:
df = pd.DataFrame(data)
print(df)

    Name  Age  Salary
0   Asad   21    9000
1  Kamil   20    6700
2   Rose   18    5688
3   Lily   19    9500

In [8]:
# 2. Basic Dataframe Understanding .

In [9]:
df.head(3) # Top Rows

    Name  Age  Salary
0   Asad   21    9000
1  Kamil   20    6700
2   Rose   18    5688

In [10]:
df.tail(2) # Bottom Rows

   Name  Age  Salary
2  Rose   18    5688
3  Lily   19    9500

In [11]:
df.shape

(4, 3)

In [12]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [13]:
df.rename(columns={'Salary':'Income'})

    Name  Age  Income
0   Asad   21    9000
1  Kamil   20    6700
2   Rose   18    5688
3   Lily   19    9500

In [14]:
df

    Name  Age  Salary
0   Asad   21    9000
1  Kamil   20    6700
2   Rose   18    5688
3   Lily   19    9500

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [16]:
df.describe()

             Age       Salary
count   4.000000     4.000000
mean   19.500000  7722.000000
std     1.290994  1823.568662
min    18.000000  5688.000000
25%    18.750000  6447.000000
50%    19.500000  7850.000000
75%    20.250000  9125.000000
max    21.000000  9500.000000

In [17]:
 # 3. Save and Load data frame csv

In [18]:
df.to_csv('Test_data.csv',index=False)

In [19]:
load_df =pd.read_csv('Test_data.csv')
load_df

    Name  Age  Salary
0   Asad   21    9000
1  Kamil   20    6700
2   Rose   18    5688
3   Lily   19    9500

In [20]:
# 4. Rows & Columns - Selection

In [21]:
df[['Name','Salary']]

    Name  Salary
0   Asad    9000
1  Kamil    6700
2   Rose    5688
3   Lily    9500

In [22]:
df[['Name']]

    Name
0   Asad
1  Kamil
2   Rose
3   Lily

In [23]:
df.loc[df.Name=='Rose']

   Name  Age  Salary
2  Rose   18    5688

In [24]:
df.loc[(df.Name=='Rose') &  (df.Salary>=5000)]

   Name  Age  Salary
2  Rose   18    5688

In [25]:
df.iloc[0]

Name      Asad
Age         21
Salary    9000
Name: 0, dtype: object

In [26]:
df.iloc[3]

Name      Lily
Age         19
Salary    9500
Name: 3, dtype: object

In [27]:
df.iloc[0:2]

    Name  Age  Salary
0   Asad   21    9000
1  Kamil   20    6700

In [28]:
# Filter Data Frames

In [29]:
df['Age']>19

0     True
1     True
2    False
3    False
Name: Age, dtype: bool

In [30]:
df[df['Age']>=21]

   Name  Age  Salary
0  Asad   21    9000

In [31]:
df_age_filter = df[df['Age']>=21]

In [32]:
print(df_age_filter)

   Name  Age  Salary
0  Asad   21    9000

In [33]:
df[(df['Age'] >=20) & (df['Salary']>=5000)]

    Name  Age  Salary
0   Asad   21    9000
1  Kamil   20    6700

In [34]:
 df.where(df['Age']>=20,other = 'Not Eligible')

           Name           Age        Salary
0          Asad            21          9000
1         Kamil            20          6700
2  Not Eligible  Not Eligible  Not Eligible
3  Not Eligible  Not Eligible  Not Eligible

In [35]:
 # 6 Operations

In [36]:
df

    Name  Age  Salary
0   Asad   21    9000
1  Kamil   20    6700
2   Rose   18    5688
3   Lily   19    9500

In [37]:
df['Team']=['Aloo','Ajeeb','Good','Bad']

In [38]:
df

    Name  Age  Salary   Team
0   Asad   21    9000   Aloo
1  Kamil   20    6700  Ajeeb
2   Rose   18    5688   Good
3   Lily   19    9500    Bad

In [39]:
df.loc[len(df)] = ['Azam', 13, 1300, 'Bhindi']
df

    Name  Age  Salary    Team
0   Asad   21    9000    Aloo
1  Kamil   20    6700   Ajeeb
2   Rose   18    5688    Good
3   Lily   19    9500     Bad
4   Azam   13    1300  Bhindi

In [40]:
df

    Name  Age  Salary    Team
0   Asad   21    9000    Aloo
1  Kamil   20    6700   Ajeeb
2   Rose   18    5688    Good
3   Lily   19    9500     Bad
4   Azam   13    1300  Bhindi

In [41]:
df.loc[0,'Salary']=95000

In [42]:
df

    Name  Age  Salary    Team
0   Asad   21   95000    Aloo
1  Kamil   20    6700   Ajeeb
2   Rose   18    5688    Good
3   Lily   19    9500     Bad
4   Azam   13    1300  Bhindi

In [43]:
df.loc[1,'Salary']=200000
df.loc[2,'Salary']=5000000
df.loc[3,'Salary']=1000000
df.loc[4,'Salary']=200000

In [44]:
df

    Name  Age   Salary    Team
0   Asad   21    95000    Aloo
1  Kamil   20   200000   Ajeeb
2   Rose   18  5000000    Good
3   Lily   19  1000000     Bad
4   Azam   13   200000  Bhindi

In [45]:
# Update value - using column value

In [46]:
df.loc[df.Name == 'Rose','Salary']=4500000

In [47]:
df

    Name  Age   Salary    Team
0   Asad   21    95000    Aloo
1  Kamil   20   200000   Ajeeb
2   Rose   18  4500000    Good
3   Lily   19  1000000     Bad
4   Azam   13   200000  Bhindi

In [48]:
 # Delete values

In [49]:
df = df.drop(df[df.Name == 'Azam'].index)

In [50]:
df

    Name  Age   Salary   Team
0   Asad   21    95000   Aloo
1  Kamil   20   200000  Ajeeb
2   Rose   18  4500000   Good
3   Lily   19  1000000    Bad

In [51]:
# Salary delete column
# df=df.drop('Salary',axis=1)
# Salary & Team delete column
# df=df.drop(['Salary','Team'],axis=1)

In [52]:
 df=df.drop('Team',axis=1)

In [53]:
df

    Name  Age   Salary
0   Asad   21    95000
1  Kamil   20   200000
2   Rose   18  4500000
3   Lily   19  1000000

In [54]:
# sort values - order values in dataframe by asc or desc order
df.sort_values('Salary') #ascending order, by default

    Name  Age   Salary
0   Asad   21    95000
1  Kamil   20   200000
3   Lily   19  1000000
2   Rose   18  4500000

In [55]:
# sort values in descending order
df.sort_values('Salary', ascending=False)

    Name  Age   Salary
2   Rose   18  4500000
3   Lily   19  1000000
1  Kamil   20   200000
0   Asad   21    95000

In [56]:
# create a date column - date of joining
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']
df

    Name  Age   Salary         DOJ
0   Asad   21    95000  2024-01-01
1  Kamil   20   200000  2024-01-15
2   Rose   18  4500000  2024-03-28
3   Lily   19  1000000  2024-03-03

In [57]:
df['DOJ'].dtype

dtype('O')

In [58]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [59]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [60]:
df

    Name  Age   Salary        DOJ
0   Asad   21    95000 2024-01-01
1  Kamil   20   200000 2024-01-15
2   Rose   18  4500000 2024-03-28
3   Lily   19  1000000 2024-03-03

In [61]:
df1=df

In [62]:
df1

    Name  Age   Salary        DOJ
0   Asad   21    95000 2024-01-01
1  Kamil   20   200000 2024-01-15
2   Rose   18  4500000 2024-03-28
3   Lily   19  1000000 2024-03-03

In [63]:
df1['DOJ2'] = ['14-01-2019','27-08-1995','05-11-2024','19-01-2007']

In [64]:
df1

    Name  Age   Salary        DOJ        DOJ2
0   Asad   21    95000 2024-01-01  14-01-2019
1  Kamil   20   200000 2024-01-15  27-08-1995
2   Rose   18  4500000 2024-03-28  05-11-2024
3   Lily   19  1000000 2024-03-03  19-01-2007

In [65]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'],format = '%d-%m-%Y' ) # change to date-time type using date-format

In [66]:
df1['DOJ2'].dtype

dtype('<M8[ns]')

In [67]:
df1['DOJ2'].dt.year
df1['DOJ2'].dt.month
df1['DOJ2'].dt.day
df1['DOJ2'].dt.day_name()

0     Monday
1     Sunday
2    Tuesday
3     Friday
Name: DOJ2, dtype: object

In [68]:
df['DOJ'] + pd.Timedelta(days=90) # add 90 days to DOJ column

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
Name: DOJ, dtype: datetime64[ns]

In [69]:
df1['DOJ2'] + pd.Timedelta(days=90)

0   2019-04-14
1   1995-11-25
2   2025-02-03
3   2007-04-19
Name: DOJ2, dtype: datetime64[ns]

In [70]:
# 8. Handling Missing Values

In [71]:
df

    Name  Age   Salary        DOJ       DOJ2
0   Asad   21    95000 2024-01-01 2019-01-14
1  Kamil   20   200000 2024-01-15 1995-08-27
2   Rose   18  4500000 2024-03-28 2024-11-05
3   Lily   19  1000000 2024-03-03 2007-01-19

In [72]:
df.isnull()

    Name    Age  Salary    DOJ   DOJ2
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False   False  False  False

In [73]:
import numpy as np

In [74]:
df.loc[df.Name =='Asad','Salary']=np.nan

In [75]:
df

    Name  Age     Salary        DOJ       DOJ2
0   Asad   21        NaN 2024-01-01 2019-01-14
1  Kamil   20   200000.0 2024-01-15 1995-08-27
2   Rose   18  4500000.0 2024-03-28 2024-11-05
3   Lily   19  1000000.0 2024-03-03 2007-01-19

In [76]:
df.isnull()

    Name    Age  Salary    DOJ   DOJ2
0  False  False    True  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False   False  False  False

In [77]:
df.isnull().sum()

Name      0
Age       0
Salary    1
DOJ       0
DOJ2      0
dtype: int64

In [78]:
df.fillna(0)

    Name  Age     Salary        DOJ       DOJ2
0   Asad   21        0.0 2024-01-01 2019-01-14
1  Kamil   20   200000.0 2024-01-15 1995-08-27
2   Rose   18  4500000.0 2024-03-28 2024-11-05
3   Lily   19  1000000.0 2024-03-03 2007-01-19

In [79]:
# 9. Aggregation and group by

In [80]:
df['Age'].value_counts()

Age
21    1
20    1
18    1
19    1
Name: count, dtype: int64

In [81]:
df[df['Age']==20].value_counts()

Name   Age  Salary    DOJ         DOJ2
Kamil  20   200000.0  2024-01-15  1995-08-27    1
Name: count, dtype: int64

In [82]:
# 10. Concatenate and Merge Dataframe (JOINs)

In [83]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [84]:
df2 = pd.DataFrame({'ID':[1,2,3,4],'Score':[98,45,33,25]})
df2

   ID  Score
0   1     98
1   2     45
2   3     33
3   4     25

In [85]:
pd.concat([df1,df2],axis=0) # Shows vertically

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   98.0
1   2  NaN   45.0
2   3  NaN   33.0
3   4  NaN   25.0

In [86]:
pd.concat([df1,df2],axis=1) # Shows rows wise

    ID Name  ID  Score
0  1.0    A   1     98
1  2.0    B   2     45
2  3.0    C   3     33
3  NaN  NaN   4     25

In [87]:
# Merge = join
pd.merge(df1,df2,how ='inner',on ='ID')

   ID Name  Score
0   1    A     98
1   2    B     45
2   3    C     33